export const INIT_CATEGORY = "INIT_CATEGORY";

export const INIT_CATEGORY_START = "INIT_CATEGORY_START";

export const INIT_CATEGORY_SUCCESS = "INIT_CATEGORY_SUCCESS";

export const INIT_CATEGORY_FAIL = "INIT_CATEGORY_FAIL";


export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

export const LOAD_PRODUCT_LIST = "LOAD_PRODUCT_LIST";

export const LOAD_PRODUCT_LIST_START = "LOAD_PRODUCT_LIST_START";

export const LOAD_PRODUCT_LIST_SUCCESS = "LOAD_PRODUCT_LIST_SUCCESS";

export const LOAD_PRODUCT_LIST_FAIL = "LOAD_PRODUCT_LIST_FAIL";


export const LOAD_PRODUCT = "LOAD_PRODUCT"

export const LOAD_PRODUCT_START = "LOAD_PRODUCT_START";

export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";

export const LOAD_PRODUCT_FAIL = "LOAD_PRODUCT_FAIL";


export const CHANGE_PAGE = "CHANGE_PAGE";





